/* Unique */
CREATE UNIQUE INDEX attribute_definition_attribute_definition_id_un ON {sc}.attribute_definition USING btree (attribute_definition_id);
CREATE UNIQUE INDEX care_site_care_site_id_un ON {sc}.care_site USING btree (care_site_id);
CREATE UNIQUE INDEX cohort_definition_cohort_definition_id_un ON {sc}.cohort_definition USING btree (cohort_definition_id);
CREATE UNIQUE INDEX concept_concept_id_un ON {sc}.concept USING btree (concept_id);
CREATE UNIQUE INDEX concept_class_concept_class_id_un ON {sc}.concept_class USING btree (concept_class_id);
CREATE UNIQUE INDEX condition_era_condition_era_id_un ON {sc}.condition_era USING btree (condition_era_id);
CREATE UNIQUE INDEX condition_occurrence_condition_occurrence_id_un ON {sc}.condition_occurrence USING btree (condition_occurrence_id);
CREATE UNIQUE INDEX cost_cost_id_un ON {sc}.cost USING btree (cost_id);
CREATE UNIQUE INDEX death_person_id_un ON {sc}.death USING btree (person_id);
CREATE UNIQUE INDEX device_exposure_device_exposure_id_un ON {sc}.device_exposure USING btree (device_exposure_id);
CREATE UNIQUE INDEX domain_domain_id_un ON {sc}.domain USING btree (domain_id);
CREATE UNIQUE INDEX dose_era_dose_era_id_un ON {sc}.dose_era USING btree (dose_era_id);
CREATE UNIQUE INDEX drug_era_drug_era_id_un ON {sc}.drug_era USING btree (drug_era_id);
CREATE UNIQUE INDEX drug_exposure_drug_exposure_id_un ON {sc}.drug_exposure USING btree (drug_exposure_id);
CREATE UNIQUE INDEX location_location_id_un ON {sc}.location USING btree (location_id);
CREATE UNIQUE INDEX measurement_measurement_id_un ON {sc}.measurement USING btree (measurement_id);
CREATE UNIQUE INDEX note_note_id_un ON {sc}.note USING btree (note_id);
CREATE UNIQUE INDEX note_nlp_note_nlp_id_un ON {sc}.note_nlp USING btree (note_nlp_id);
CREATE UNIQUE INDEX observation_observation_id_un ON {sc}.observation USING btree (observation_id);
CREATE UNIQUE INDEX observation_period_observation_period_id_un ON {sc}.observation_period USING btree (observation_period_id);
CREATE UNIQUE INDEX payer_plan_period_payer_plan_period_id_un ON {sc}.payer_plan_period USING btree (payer_plan_period_id);
CREATE UNIQUE INDEX person_person_id_un ON {sc}.person USING btree (person_id);
CREATE UNIQUE INDEX procedure_occurrence_procedure_occurrence_id_un ON {sc}.procedure_occurrence USING btree (procedure_occurrence_id);
CREATE UNIQUE INDEX provider_provider_id_un ON {sc}.provider USING btree (provider_id);
CREATE UNIQUE INDEX relationship_relationship_id_un ON {sc}.relationship USING btree (relationship_id);
CREATE UNIQUE INDEX specimen_specimen_id_un ON {sc}.specimen USING btree (specimen_id);
CREATE UNIQUE INDEX visit_detail_visit_detail_id_un ON {sc}.visit_detail USING btree (visit_detail_id);
CREATE UNIQUE INDEX visit_occurrence_visit_occurrence_id_un ON {sc}.visit_occurrence USING btree (visit_occurrence_id);
CREATE UNIQUE INDEX vocabulary_vocabulary_id_un ON {sc}.vocabulary USING btree (vocabulary_id);

/*  Indexes */
CREATE INDEX visit_occurrence_person_id_idx ON {sc}.visit_occurrence USING btree (person_id);
CREATE INDEX visit_occurrence_visit_concept_id_idx ON {sc}.visit_occurrence USING btree (visit_concept_id);
CREATE INDEX visit_occurrence_visit_type_concept_id_idx ON {sc}.visit_occurrence USING btree (visit_type_concept_id);
CREATE INDEX visit_occurrence_provider_id_idx ON {sc}.visit_occurrence USING btree (provider_id);
CREATE INDEX visit_occurrence_care_site_id_idx ON {sc}.visit_occurrence USING btree (care_site_id);
CREATE INDEX visit_occurrence_visit_source_concept_id_idx ON {sc}.visit_occurrence USING btree (visit_source_concept_id);
CREATE INDEX visit_occurrence_admitting_source_concept_id_idx ON {sc}.visit_occurrence USING btree (admitting_source_concept_id);
CREATE INDEX visit_occurrence_discharge_to_concept_id_idx ON {sc}.visit_occurrence USING btree (discharge_to_concept_id);
CREATE INDEX visit_detail_person_id_idx ON {sc}.visit_detail USING btree (person_id);
CREATE INDEX visit_detail_visit_detail_concept_id_idx ON {sc}.visit_detail USING btree (visit_detail_concept_id);
CREATE INDEX visit_detail_visit_detail_type_concept_id_idx ON {sc}.visit_detail USING btree (visit_detail_type_concept_id);
CREATE INDEX visit_detail_provider_id_idx ON {sc}.visit_detail USING btree (provider_id);
CREATE INDEX visit_detail_care_site_id_idx ON {sc}.visit_detail USING btree (care_site_id);
CREATE INDEX visit_detail_admitting_source_concept_id_idx ON {sc}.visit_detail USING btree (admitting_source_concept_id);
CREATE INDEX visit_detail_discharge_to_concept_id_idx ON {sc}.visit_detail USING btree (discharge_to_concept_id);
CREATE INDEX visit_detail_preceding_visit_detail_id_idx ON {sc}.visit_detail USING btree (preceding_visit_detail_id);
CREATE INDEX visit_detail_visit_detail_source_concept_id_idx ON {sc}.visit_detail USING btree (visit_detail_source_concept_id);
CREATE INDEX visit_detail_visit_detail_parent_id_idx ON {sc}.visit_detail USING btree (visit_detail_parent_id);
CREATE INDEX visit_detail_visit_occurrence_id_idx ON {sc}.visit_detail USING btree (visit_occurrence_id);
CREATE INDEX specimen_person_id_idx ON {sc}.specimen USING btree (person_id);
CREATE INDEX specimen_specimen_concept_id_idx ON {sc}.specimen USING btree (specimen_concept_id);
CREATE INDEX specimen_specimen_type_concept_id_idx ON {sc}.specimen USING btree (specimen_type_concept_id);
CREATE INDEX specimen_unit_concept_id_idx ON {sc}.specimen USING btree (unit_concept_id);
CREATE INDEX specimen_anatomic_site_concept_id_idx ON {sc}.specimen USING btree (anatomic_site_concept_id);
CREATE INDEX specimen_disease_status_concept_id_idx ON {sc}.specimen USING btree (disease_status_concept_id);
CREATE INDEX specimen_specimen_source_id_idx ON {sc}.specimen USING btree (specimen_source_id);
CREATE INDEX source_to_concept_map_source_code_idx ON {sc}.source_to_concept_map USING btree (source_code);
CREATE INDEX source_to_concept_map_source_concept_id_idx ON {sc}.source_to_concept_map USING btree (source_concept_id);
CREATE INDEX source_to_concept_map_source_vocabulary_id_idx ON {sc}.source_to_concept_map USING btree (source_vocabulary_id);
CREATE INDEX source_to_concept_map_target_concept_id_idx ON {sc}.source_to_concept_map USING btree (target_concept_id);
CREATE INDEX source_to_concept_map_target_vocabulary_id_idx ON {sc}.source_to_concept_map USING btree (target_vocabulary_id);
CREATE INDEX relationship_reverse_relationship_id_idx ON {sc}.relationship USING btree (reverse_relationship_id);
CREATE INDEX relationship_relationship_concept_id_idx ON {sc}.relationship USING btree (relationship_concept_id);
CREATE INDEX provider_specialty_concept_id_idx ON {sc}.provider USING btree (specialty_concept_id);
CREATE INDEX provider_care_site_id_idx ON {sc}.provider USING btree (care_site_id);
CREATE INDEX provider_gender_concept_id_idx ON {sc}.provider USING btree (gender_concept_id);
CREATE INDEX provider_specialty_source_concept_id_idx ON {sc}.provider USING btree (specialty_source_concept_id);
CREATE INDEX provider_gender_source_concept_id_idx ON {sc}.provider USING btree (gender_source_concept_id);
CREATE INDEX procedure_occurrence_person_id_idx ON {sc}.procedure_occurrence USING btree (person_id);
CREATE INDEX procedure_occurrence_procedure_concept_id_idx ON {sc}.procedure_occurrence USING btree (procedure_concept_id);
CREATE INDEX procedure_occurrence_procedure_type_concept_id_idx ON {sc}.procedure_occurrence USING btree (procedure_type_concept_id);
CREATE INDEX procedure_occurrence_modifier_concept_id_idx ON {sc}.procedure_occurrence USING btree (modifier_concept_id);
CREATE INDEX procedure_occurrence_provider_id_idx ON {sc}.procedure_occurrence USING btree (provider_id);
CREATE INDEX procedure_occurrence_visit_occurrence_id_idx ON {sc}.procedure_occurrence USING btree (visit_occurrence_id);
CREATE INDEX procedure_occurrence_visit_detail_id_idx ON {sc}.procedure_occurrence USING btree (visit_detail_id);
CREATE INDEX procedure_occurrence_procedure_source_concept_id_idx ON {sc}.procedure_occurrence USING btree (procedure_source_concept_id);
CREATE INDEX person_gender_concept_id_idx ON {sc}.person USING btree (gender_concept_id);
CREATE INDEX person_race_concept_id_idx ON {sc}.person USING btree (race_concept_id);
CREATE INDEX person_ethnicity_concept_id_idx ON {sc}.person USING btree (ethnicity_concept_id);
CREATE INDEX person_location_id_idx ON {sc}.person USING btree (location_id);
CREATE INDEX person_provider_id_idx ON {sc}.person USING btree (provider_id);
CREATE INDEX person_care_site_id_idx ON {sc}.person USING btree (care_site_id);
CREATE INDEX person_gender_source_concept_id_idx ON {sc}.person USING btree (gender_source_concept_id);
CREATE INDEX person_race_source_concept_id_idx ON {sc}.person USING btree (race_source_concept_id);
CREATE INDEX person_ethnicity_source_concept_id_idx ON {sc}.person USING btree (ethnicity_source_concept_id);
CREATE INDEX payer_plan_period_person_id_idx ON {sc}.payer_plan_period USING btree (person_id);
CREATE INDEX payer_plan_period_payer_concept_id_idx ON {sc}.payer_plan_period USING btree (payer_concept_id);
CREATE INDEX payer_plan_period_payer_source_concept_id_idx ON {sc}.payer_plan_period USING btree (payer_source_concept_id);
CREATE INDEX payer_plan_period_plan_concept_id_idx ON {sc}.payer_plan_period USING btree (plan_concept_id);
CREATE INDEX payer_plan_period_plan_source_concept_id_idx ON {sc}.payer_plan_period USING btree (plan_source_concept_id);
CREATE INDEX payer_plan_period_sponsor_concept_id_idx ON {sc}.payer_plan_period USING btree (sponsor_concept_id);
CREATE INDEX payer_plan_period_sponsor_source_concept_id_idx ON {sc}.payer_plan_period USING btree (sponsor_source_concept_id);
CREATE INDEX payer_plan_period_stop_reason_concept_id_idx ON {sc}.payer_plan_period USING btree (stop_reason_concept_id);
CREATE INDEX payer_plan_period_stop_reason_source_concept_id_idx ON {sc}.payer_plan_period USING btree (stop_reason_source_concept_id);
CREATE INDEX observation_period_person_id_idx ON {sc}.observation_period USING btree (person_id);
CREATE INDEX observation_period_period_type_concept_id_idx ON {sc}.observation_period USING btree (period_type_concept_id);
CREATE INDEX observation_person_id_idx ON {sc}.observation USING btree (person_id);
CREATE INDEX observation_observation_concept_id_idx ON {sc}.observation USING btree (observation_concept_id);
CREATE INDEX observation_observation_type_concept_id_idx ON {sc}.observation USING btree (observation_type_concept_id);
CREATE INDEX observation_value_as_concept_id_idx ON {sc}.observation USING btree (value_as_concept_id);
CREATE INDEX observation_qualifier_concept_id_idx ON {sc}.observation USING btree (qualifier_concept_id);
CREATE INDEX observation_unit_concept_id_idx ON {sc}.observation USING btree (unit_concept_id);
CREATE INDEX observation_provider_id_idx ON {sc}.observation USING btree (provider_id);
CREATE INDEX observation_visit_occurrence_id_idx ON {sc}.observation USING btree (visit_occurrence_id);
CREATE INDEX observation_visit_detail_id_idx ON {sc}.observation USING btree (visit_detail_id);
CREATE INDEX observation_observation_source_concept_id_idx ON {sc}.observation USING btree (observation_source_concept_id);
CREATE INDEX note_nlp_note_id_idx ON {sc}.note_nlp USING btree (note_id);
CREATE INDEX note_nlp_section_concept_id_idx ON {sc}.note_nlp USING btree (section_concept_id);
CREATE INDEX note_nlp_note_nlp_concept_id_idx ON {sc}.note_nlp USING btree (note_nlp_concept_id);
CREATE INDEX note_nlp_note_nlp_source_concept_id_idx ON {sc}.note_nlp USING btree (note_nlp_source_concept_id);
CREATE INDEX note_person_id_idx ON {sc}.note USING btree (person_id);
CREATE INDEX note_note_type_concept_id_idx ON {sc}.note USING btree (note_type_concept_id);
CREATE INDEX note_note_class_concept_id_idx ON {sc}.note USING btree (note_class_concept_id);
CREATE INDEX note_encoding_concept_id_idx ON {sc}.note USING btree (encoding_concept_id);
CREATE INDEX note_language_concept_id_idx ON {sc}.note USING btree (language_concept_id);
CREATE INDEX note_provider_id_idx ON {sc}.note USING btree (provider_id);
CREATE INDEX note_visit_occurrence_id_idx ON {sc}.note USING btree (visit_occurrence_id);
CREATE INDEX note_visit_detail_id_idx ON {sc}.note USING btree (visit_detail_id);
CREATE INDEX metadata_tmp_person_id_idx ON {sc}.metadata_tmp USING btree (person_id);
CREATE INDEX metadata_metadata_concept_id_idx ON {sc}.metadata USING btree (metadata_concept_id);
CREATE INDEX metadata_metadata_type_concept_id_idx ON {sc}.metadata USING btree (metadata_type_concept_id);
CREATE INDEX metadata_value_as_concept_id_idx ON {sc}.metadata USING btree (value_as_concept_id);
CREATE INDEX measurement_person_id_idx ON {sc}.measurement USING btree (person_id);
CREATE INDEX measurement_measurement_concept_id_idx ON {sc}.measurement USING btree (measurement_concept_id);
CREATE INDEX measurement_measurement_type_concept_id_idx ON {sc}.measurement USING btree (measurement_type_concept_id);
CREATE INDEX measurement_operator_concept_id_idx ON {sc}.measurement USING btree (operator_concept_id);
CREATE INDEX measurement_value_as_concept_id_idx ON {sc}.measurement USING btree (value_as_concept_id);
CREATE INDEX measurement_unit_concept_id_idx ON {sc}.measurement USING btree (unit_concept_id);
CREATE INDEX measurement_provider_id_idx ON {sc}.measurement USING btree (provider_id);
CREATE INDEX measurement_visit_occurrence_id_idx ON {sc}.measurement USING btree (visit_occurrence_id);
CREATE INDEX measurement_visit_detail_id_idx ON {sc}.measurement USING btree (visit_detail_id);
CREATE INDEX measurement_measurement_source_concept_id_idx ON {sc}.measurement USING btree (measurement_source_concept_id);
CREATE INDEX location_city_idx ON {sc}.location USING btree (city);
CREATE INDEX location_state_idx ON {sc}.location USING btree (state);
CREATE INDEX location_zip_idx ON {sc}.location USING btree (zip);
CREATE INDEX location_county_idx ON {sc}.location USING btree (county);
CREATE INDEX fact_relationship_domain_concept_id_1_idx ON {sc}.fact_relationship USING btree (domain_concept_id_1);
CREATE INDEX fact_relationship_fact_id_1_idx ON {sc}.fact_relationship USING btree (fact_id_1);
CREATE INDEX fact_relationship_domain_concept_id_2_idx ON {sc}.fact_relationship USING btree (domain_concept_id_2);
CREATE INDEX fact_relationship_fact_id_2_idx ON {sc}.fact_relationship USING btree (fact_id_2);
CREATE INDEX fact_relationship_relationship_concept_id_idx ON {sc}.fact_relationship USING btree (relationship_concept_id);
CREATE INDEX drug_strength_drug_concept_id_idx ON {sc}.drug_strength USING btree (drug_concept_id);
CREATE INDEX drug_strength_ingredient_concept_id_idx ON {sc}.drug_strength USING btree (ingredient_concept_id);
CREATE INDEX drug_strength_amount_unit_concept_id_idx ON {sc}.drug_strength USING btree (amount_unit_concept_id);
CREATE INDEX drug_strength_numerator_unit_concept_id_idx ON {sc}.drug_strength USING btree (numerator_unit_concept_id);
CREATE INDEX drug_strength_denominator_unit_concept_id_idx ON {sc}.drug_strength USING btree (denominator_unit_concept_id);
CREATE INDEX drug_exposure_person_id_idx ON {sc}.drug_exposure USING btree (person_id);
CREATE INDEX drug_exposure_drug_concept_id_idx ON {sc}.drug_exposure USING btree (drug_concept_id);
CREATE INDEX drug_exposure_drug_type_concept_id_idx ON {sc}.drug_exposure USING btree (drug_type_concept_id);
CREATE INDEX drug_exposure_route_concept_id_idx ON {sc}.drug_exposure USING btree (route_concept_id);
CREATE INDEX drug_exposure_provider_id_idx ON {sc}.drug_exposure USING btree (provider_id);
CREATE INDEX drug_exposure_visit_occurrence_id_idx ON {sc}.drug_exposure USING btree (visit_occurrence_id);
CREATE INDEX drug_exposure_visit_detail_id_idx ON {sc}.drug_exposure USING btree (visit_detail_id);
CREATE INDEX drug_exposure_drug_source_concept_id_idx ON {sc}.drug_exposure USING btree (drug_source_concept_id);
CREATE INDEX drug_era_person_id_idx ON {sc}.drug_era USING btree (person_id);
CREATE INDEX drug_era_drug_concept_id_idx ON {sc}.drug_era USING btree (drug_concept_id);
CREATE INDEX dose_era_person_id_idx ON {sc}.dose_era USING btree (person_id);
CREATE INDEX dose_era_drug_concept_id_idx ON {sc}.dose_era USING btree (drug_concept_id);
CREATE INDEX dose_era_unit_concept_id_idx ON {sc}.dose_era USING btree (unit_concept_id);
CREATE INDEX domain_domain_concept_id_idx ON {sc}.domain USING btree (domain_concept_id);
CREATE INDEX device_exposure_person_id_idx ON {sc}.device_exposure USING btree (person_id);
CREATE INDEX device_exposure_device_concept_id_idx ON {sc}.device_exposure USING btree (device_concept_id);
CREATE INDEX device_exposure_device_type_concept_id_idx ON {sc}.device_exposure USING btree (device_type_concept_id);
CREATE INDEX device_exposure_unique_device_id_idx ON {sc}.device_exposure USING btree (unique_device_id);
CREATE INDEX device_exposure_provider_id_idx ON {sc}.device_exposure USING btree (provider_id);
CREATE INDEX device_exposure_visit_occurrence_id_idx ON {sc}.device_exposure USING btree (visit_occurrence_id);
CREATE INDEX device_exposure_visit_detail_id_idx ON {sc}.device_exposure USING btree (visit_detail_id);
CREATE INDEX device_exposure_device_source_concept_id_idx ON {sc}.device_exposure USING btree (device_source_concept_id);
CREATE INDEX death_death_type_concept_id_idx ON {sc}.death USING btree (death_type_concept_id);
CREATE INDEX death_cause_concept_id_idx ON {sc}.death USING btree (cause_concept_id);
CREATE INDEX death_cause_source_concept_id_idx ON {sc}.death USING btree (cause_source_concept_id);
CREATE INDEX cost_cost_event_id_idx ON {sc}.cost USING btree (cost_event_id);
CREATE INDEX cost_cost_domain_id_idx ON {sc}.cost USING btree (cost_domain_id);
CREATE INDEX cost_cost_type_concept_id_idx ON {sc}.cost USING btree (cost_type_concept_id);
CREATE INDEX cost_currency_concept_id_idx ON {sc}.cost USING btree (currency_concept_id);
CREATE INDEX cost_payer_plan_period_id_idx ON {sc}.cost USING btree (payer_plan_period_id);
CREATE INDEX cost_revenue_code_concept_id_idx ON {sc}.cost USING btree (revenue_code_concept_id);
CREATE INDEX cost_drg_concept_id_idx ON {sc}.cost USING btree (drg_concept_id);
CREATE INDEX condition_occurrence_person_id_idx ON {sc}.condition_occurrence USING btree (person_id);
CREATE INDEX condition_occurrence_condition_concept_id_idx ON {sc}.condition_occurrence USING btree (condition_concept_id);
CREATE INDEX condition_occurrence_condition_type_concept_id_idx ON {sc}.condition_occurrence USING btree (condition_type_concept_id);
CREATE INDEX condition_occurrence_provider_id_idx ON {sc}.condition_occurrence USING btree (provider_id);
CREATE INDEX condition_occurrence_visit_occurrence_id_idx ON {sc}.condition_occurrence USING btree (visit_occurrence_id);
CREATE INDEX condition_occurrence_visit_detail_id_idx ON {sc}.condition_occurrence USING btree (visit_detail_id);
CREATE INDEX condition_occurrence_condition_status_concept_id_idx ON {sc}.condition_occurrence USING btree (condition_status_concept_id);
CREATE INDEX condition_occurrence_condition_source_concept_id_idx ON {sc}.condition_occurrence USING btree (condition_source_concept_id);
CREATE INDEX condition_era_person_id_idx ON {sc}.condition_era USING btree (person_id);
CREATE INDEX condition_era_condition_concept_id_idx ON {sc}.condition_era USING btree (condition_concept_id);
CREATE INDEX concept_synonym_concept_id_idx ON {sc}.concept_synonym USING btree (concept_id);
CREATE INDEX concept_synonym_language_concept_id_idx ON {sc}.concept_synonym USING btree (language_concept_id);
CREATE INDEX concept_relationship_concept_id_1_idx ON {sc}.concept_relationship USING btree (concept_id_1);
CREATE INDEX concept_relationship_concept_id_2_idx ON {sc}.concept_relationship USING btree (concept_id_2);
CREATE INDEX concept_relationship_relationship_id_idx ON {sc}.concept_relationship USING btree (relationship_id);
CREATE INDEX concept_class_concept_class_concept_id_idx ON {sc}.concept_class USING btree (concept_class_concept_id);
CREATE INDEX concept_ancestor_ancestor_concept_id_idx ON {sc}.concept_ancestor USING btree (ancestor_concept_id);
CREATE INDEX concept_ancestor_descendant_concept_id_idx ON {sc}.concept_ancestor USING btree (descendant_concept_id);
CREATE INDEX concept_domain_id_idx ON {sc}.concept USING btree (domain_id);
CREATE INDEX concept_vocabulary_id_idx ON {sc}.concept USING btree (vocabulary_id);
CREATE INDEX concept_concept_class_id_idx ON {sc}.concept USING btree (concept_class_id);
CREATE INDEX cohort_definition_definition_type_concept_id_idx ON {sc}.cohort_definition USING btree (definition_type_concept_id);
CREATE INDEX cohort_definition_subject_concept_id_idx ON {sc}.cohort_definition USING btree (subject_concept_id);
CREATE INDEX cohort_attribute_subject_id_idx ON {sc}.cohort_attribute USING btree (subject_id);
CREATE INDEX cohort_attribute_attribute_definition_id_idx ON {sc}.cohort_attribute USING btree (attribute_definition_id);
CREATE INDEX cohort_attribute_value_as_concept_id_idx ON {sc}.cohort_attribute USING btree (value_as_concept_id);
CREATE INDEX cohort_cohort_definition_id_idx ON {sc}.cohort USING btree (cohort_definition_id);
CREATE INDEX cohort_subject_id_idx ON {sc}.cohort USING btree (subject_id);
CREATE INDEX cdm_source_cdm_source_name_idx ON {sc}.cdm_source USING btree (cdm_source_name);
CREATE INDEX cdm_source_cdm_source_abbreviation_idx ON {sc}.cdm_source USING btree (cdm_source_abbreviation);
CREATE INDEX cdm_domain_meta_domain_id_idx ON {sc}.cdm_domain_meta USING btree (domain_id);
CREATE INDEX care_site_place_of_service_concept_id_idx ON {sc}.care_site USING btree (place_of_service_concept_id);
CREATE INDEX care_site_location_id_idx ON {sc}.care_site USING btree (location_id);
CREATE INDEX attribute_definition_attribute_type_concept_id_idx ON {sc}.attribute_definition USING btree (attribute_type_concept_id);